FROM php:8.2-fpm


RUN apt-get update && apt-get install -y \
    zip unzip git curl libzip-dev libpq-dev \
    && docker-php-ext-install pdo pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/wfhart

COPY . .

CMD php -S 0.0.0.0:9000 -t public