name: 🚀 Deploy to VPS (prod)

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."                       # ce qu’on envoie
          target: "/var/www/wfhart"         # répertoire sur le VPS

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /var/www/wfhart
            echo "📦 Pulling last images"
            docker compose pull
            echo "🛑 Stopping old containers"
            docker compose down
            echo "🚀 Starting new containers"
            docker compose up -d --build
            echo "✅ Deployment complete"
